//src/lib/mockData.ts
export const mockPosts = [
  {
    id: '1',
    title: 'Teclado Mecânico RGB',
    price: 499.90,
    description: 'Teclado mecânico com iluminação RGB personalizável e switches silenciosos.',
    img: 'https://cdn.awsli.com.br/2500x2500/1318/1318167/produto/301622057/k653-rgb-2-8825-pt-brown-9knemk9rjh.png',
  },
  {
    id: '2',
    title: 'Mouse Gamer Wireless',
    price: 299.90,
    description: 'Mouse gamer sem fio com alta precisão e autonomia de bateria estendida.',
    img: 'https://cdn.shoppub.io/cdn-cgi/image/w=600,h=600,q=80,f=auto/oficinadosbits/media/uploads/produtos/foto/ejiiumos/file.png',
  },
  {
    id: '3',
    title: 'Monitor 27" 4K',
    price: 1799.00,
    description: 'Monitor 27 polegadas com resolução 4K UHD e cores vibrantes.',
    img: 'https://cdn.awsli.com.br/2500x2500/954/954868/produto/74341567/0786d63614.jpg',
  },
  {
    id: '4',
    title: 'Headset RGB com Microfone',
    price: 229.50,
    description: 'Headset confortável com som surround 7.1 e microfone removível.',
    img: 'https://cdn.shoppub.io/cdn-cgi/image/w=1000,h=1000,q=80,f=auto/oficinadosbits/media/uploads/produtos/foto/lcunpvzb/file.png',
  },
  {
    id: '5',
    title: 'Cadeira Gamer Ergonômica',
    price: 999.00,
    description: 'Cadeira gamer com suporte lombar e ajuste de altura para máximo conforto.',
    img: 'https://images.tcdn.com.br/img/img_prod/631328/cadeira_gamer_stillus_ergonomica_com_apoio_para_os_pes_oficial_webshop_5815_2_64e7cdf787e46f7ab24bc5366a815dbc.jpeg',
  },
  {
    id: '6',
    title: 'SSD 1TB NVMe',
    price: 699.00,
    description: 'SSD ultrarrápido NVMe com 1TB de armazenamento para jogos e programas.',
    img: 'https://images5.kabum.com.br/produtos/fotos/380745/ssd-kingston-nv2-1-tb-m-2-2280-pcie-nvme-leitura-2-100-mb-s-e-gravacao-1-700-mb-s-snv2s-1000g_1666033118_gg.jpg',
  },
  {
    id: '7',
    title: 'Placa de Vídeo RTX 3060',
    price: 3500.00,
    description: 'Placa de vídeo NVIDIA RTX 3060 com ray tracing e desempenho para jogos AAA.',
    img: 'https://cdn.shoppub.io/cdn-cgi/image/w=1000,h=1000,q=80,f=auto/oficinadosbits/media/uploads/produtos/foto/lqxchwua/file.png',
  },
  {
    id: '8',
    title: 'Fonte 650W 80 Plus Gold',
    price: 450.00,
    description: 'Fonte de alimentação eficiente com certificação 80 Plus Gold.',
    img: 'https://images.kabum.com.br/produtos/fotos/103280/fonte-xpg-core-reactor-650w-80-plus-gold-modular_fonte-xpg-core-reactor-650w-80-plus-gold-modular_1571153114_gg.jpg',
  },
  {
    id: '9',
    title: 'Gabinete Gamer RGB',
    price: 399.00,
    description: 'Gabinete com ventilação otimizada e iluminação RGB personalizável.',
    img: 'https://cdn.shoppub.io/cdn-cgi/image/w=1000,h=1000,q=80,f=auto/oficinadosbits/media/uploads/produtos/foto/udyzakyx/file.png',
  },
  {
    id: '10',
    title: 'Cooler para CPU RGB',
    price: 179.90,
    description: 'Cooler para processador com iluminação RGB e alta eficiência térmica.',
    img: 'https://m.media-amazon.com/images/I/71C27G6zzaL.jpg',
  },
  
  {
    id: '11',
    title: 'Webcam Full HD',
    price: 229.90,
    description: 'Webcam Full HD para videoconferências com microfone embutido.',
    img: 'https://www.wb.com.br/upload/produto/imagem/22-WEBCAMWB-1.webp',
  },
  {
    id: '12',
    title: 'Teclado Gamer Mecânico',
    price: 599.00,
    description: 'Teclado mecânico com switches táteis e iluminação RGB dinâmica.',
    img: 'https://images.tcdn.com.br/img/img_prod/745260/teclado_gamer_mecanico_blue_switch_led_rgb_usb_pc_ps4_xbox_71_1_37b42f241e6a0881a2cb1709695f9091.jpg',
  },
  {
    id: '13',
    title: 'Mousepad Gamer Grande',
    price: 79.90,
    description: 'Mousepad de grande tamanho com superfície antiaderente.',
    img: 'https://cdn.shoppub.io/cdn-cgi/image/w=1000,h=1000,q=80,f=auto/oficinadosbits/media/uploads/produtos/foto/ajeotfxs/file.png',
  },
  {
    id: '14',
    title: 'Monitor Curvo 24" Full HD',
    price: 999.00,
    description: 'Monitor curvo de 24 polegadas com resolução Full HD para imersão total.',
    img: 'https://i.zst.com.br/thumbs/12/b/2c/1682040120.jpg',
  },
];

