//src/lib/mockData.ts
export const mockPosts = [
  {
    id: '1',
    title: 'Teclado Mecânico RGB',
    price: 499.90,
    description: 'Teclado mecânico com iluminação RGB personalizável e switches silenciosos.',
    img: 'https://example.com/images/teclado1.jpg',
  },
  {
    id: '2',
    title: 'Mouse Gamer Wireless',
    price: 299.90,
    description: 'Mouse gamer sem fio com alta precisão e autonomia de bateria estendida.',
    img: 'https://example.com/images/mouse1.jpg',
  },
  {
    id: '3',
    title: 'Monitor 27" 4K',
    price: 1799.00,
    description: 'Monitor 27 polegadas com resolução 4K UHD e cores vibrantes.',
    img: 'https://example.com/images/monitor1.jpg',
  },
  {
    id: '4',
    title: 'Headset RGB com Microfone',
    price: 229.50,
    description: 'Headset confortável com som surround 7.1 e microfone removível.',
    img: 'https://example.com/images/headset1.jpg',
  },
  {
    id: '5',
    title: 'Cadeira Gamer Ergonômica',
    price: 999.00,
    description: 'Cadeira gamer com suporte lombar e ajuste de altura para máximo conforto.',
    img: 'https://example.com/images/cadeira1.jpg',
  },
  {
    id: '6',
    title: 'SSD 1TB NVMe',
    price: 699.00,
    description: 'SSD ultrarrápido NVMe com 1TB de armazenamento para jogos e programas.',
    img: 'https://example.com/images/ssd1tb.jpg',
  },
  {
    id: '7',
    title: 'Placa de Vídeo RTX 3060',
    price: 3500.00,
    description: 'Placa de vídeo NVIDIA RTX 3060 com ray tracing e desempenho para jogos AAA.',
    img: 'https://example.com/images/rtx3060.jpg',
  },
  {
    id: '8',
    title: 'Fonte 650W 80 Plus Gold',
    price: 450.00,
    description: 'Fonte de alimentação eficiente com certificação 80 Plus Gold.',
    img: 'https://example.com/images/fonte650w.jpg',
  },
  {
    id: '9',
    title: 'Gabinete Gamer RGB',
    price: 399.00,
    description: 'Gabinete com ventilação otimizada e iluminação RGB personalizável.',
    img: 'https://example.com/images/gabinete1.jpg',
  },
  {
    id: '10',
    title: 'Cooler para CPU RGB',
    price: 179.90,
    description: 'Cooler para processador com iluminação RGB e alta eficiência térmica.',
    img: 'https://example.com/images/cooler1.jpg',
  },
  {
    id: '11',
    title: 'Memória RAM 16GB DDR4',
    price: 649.00,
    description: 'Kit de 16GB DDR4 para alto desempenho em multitarefa e jogos.',
    img: 'https://example.com/images/ram16gb.jpg',
  },
  {
    id: '12',
    title: 'Webcam Full HD',
    price: 229.90,
    description: 'Webcam Full HD para videoconferências com microfone embutido.',
    img: 'https://example.com/images/webcam1.jpg',
  },
  {
    id: '13',
    title: 'Teclado Gamer Mecânico',
    price: 599.00,
    description: 'Teclado mecânico com switches táteis e iluminação RGB dinâmica.',
    img: 'https://example.com/images/teclado2.jpg',
  },
  {
    id: '14',
    title: 'Mousepad Gamer Grande',
    price: 79.90,
    description: 'Mousepad de grande tamanho com superfície antiaderente.',
    img: 'https://example.com/images/mousepad1.jpg',
  },
  {
    id: '15',
    title: 'Monitor Curvo 24" Full HD',
    price: 999.00,
    description: 'Monitor curvo de 24 polegadas com resolução Full HD para imersão total.',
    img: 'https://example.com/images/monitor24curvo.jpg',
  },
];
